### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by MeggyCal** [wq/django-swappable-models#19]
Python 3.7 is nowadays the most commonly used python3 version. But the tests fail:

[    8s]   File "/home/abuild/rpmbuild/BUILD/django-swappable-models-1.1.0/tests/default_app/models.py", line 18, in Item
[    8s]     type = models.ForeignKey(swapper.get_model_name('default_app', "Type"))
[    8s] TypeError: __init__() missing 1 required positional argument: 'on_delete'

Could you please make the software compatible with Python 3.7? Thank you.

**Comment by fsequence** [comment]
Hey man, I have been swamped. Going to be making sure everything is A okay this weekend. I thought you were gonna have an issue with the (maybe)extra Verbose name in the 'CustomUser Model' but what you sent me looks like you're attaching a foreign key and django is asking you to provide one of its required arguments, on_delete=models.CASCADE or on_delete=models.SET_NULL(null must be set to true) or https://docs.djangoproject.com/en/1.11/ref/models/fields/#arguments . Do me a favor hit that like or star🌟 on my page, 😀

⁣Sent from BlueMail ​

**Comment by MeggyCal** [comment]
Thanks, it helped. I noticed I was using Django 2.2.2 on Python 3, which is too new and has this behaviour deprecated. Sorry I did not tell you. The tests now run OK.

It could be nice to integrate Django2 (as soon an python2 will reach EOL), but take your time :) . Thank you for your help.

**Comment by MeggyCal** [comment]
Here you have star: :star2: . I did not find any other way how to react with a star :) .

**Comment by sheppard** [comment]
Thanks, the tests are updated in version 1.1.1 (see #17).
