### ISSUE TITLE
Inherited swapped model ?

### ISSUE THREAD

**Issue by Pawamoy** [wq/django-swappable-models#3]
What if I want to write a model that inherit a swapped model?
I can't use
```python
class Child(swapper.get_model_name('reusableapp', 'Parent')):
    ...
```
because it won't accept a string as model base.
I can't use `swapper.load_model(...)` neither (as explained in the README).

Do you have any idea on how to do this?
I want people that use my app to be able to add custom fields in a base model that is inherited by other models of my app. I can't ask them to swap all of the models :hamster:

**Comment by sheppard** [comment]
This is a bit tricky, but should be doable.  The solution depends on whether or not your base model is `abstract`.  Swapper and the underlying Django mechanism are intended to be used to swap out concrete models (though swappable models usually extend an abstract base).

#### Abstract Base Model
If the base model you want to swap is itself abstract, you might not need to implement it as a `swappable` model per se.  Instead, you could have the user create an abstract model extending your abstract model, and then have your concrete models extend the user's abstract model.  The main challenge is that you'll need to set up your classes in such a way as to avoid recursive imports.  You could probably do something like this:

```python
# reusable_app/abstract_models.py
class BaseModel(models.Model):
    # (essential fields here)
    class Meta:
        abstract = True
```

```python
# reusable_app/models.py

# Determine abstract base class from settings
from django.conf import settings
class_name = getattr(
    settings,
    "REUSABLE_APP_BASE_MODEL",
    "reusable_app.abstract_models.BaseModel"
)

# If you're already using rest_framework, import_from_string() is handy;
# otherwise it's fairly easy to implement
from rest_framework.settings import import_from_string
BaseModel = import_from_string(class_name, "REUSABLE_APP_BASE_MODEL")

class Model1(BaseModel):
     # ...

class Model2(BaseModel):
     # ...
```

```python
# user_app/models.py
from reusable_app.abstract_models import BaseModel as ReusableBaseModel

class BaseModel(ReusableBaseModel):
    # (extra fields here)
    class Meta:
        abstract = True
```

```python
# user_project/settings.py
REUSABLE_APP_BASE_MODEL="user_app.BaseModel"
```

#### Concrete Base Model
If your base model is *not* abstract, then Django is creating a `OneToOneField` to connect all of the inheriting models to the base model.  In that case, you could explicitly define a `OneToOneField` pointer with the `swapper` syntax:

```python
# reusable_app/models.py
from django.db import models
import swapper

class AbstractBaseModel(models.Model):
    # (essential fields here)
    class Meta:
        abstract = True

class BaseModel(AbstractBaseModel):
    class Meta:
        swappable = swapper.swappable_setting('reusable_app', 'BaseModel')

class BasePtrModel(models.Model):
    base_ptr = models.OneToOneField(swapper.get_model_name('reusable_app', 'BaseModel')
    class Meta:
        abstract = True

class Model1(BasePtrModel):
    # ...

class Model2(BasePtrModel):
    # ...
```

```python
# user_app/models.py
from reusable_app.models import AbstractBaseModel
class BaseModel(AbstractBaseModel):
    # (extra fields here)
```

```python
# user_project/settings.py
REUSABLE_APP_BASE_MODEL="user_app.BaseModel"
```

**Comment by Pawamoy** [comment]
Thank you for your answer. I did not try what you described because I do not need my app to be reusable anymore. But this will be very useful if I need it for another app in the future!
