### ISSUE TITLE
django.db.models.get_model is deprecated

### ISSUE THREAD

**Issue by sheppard** [wq/django-swappable-models#6]
The alias will be dropped in Django 1.9.  Just need to update `swapper.load_model` to use `django.db.models.loading.get_model` instead.

**Comment by mauritsvanrees** [comment]
Using `django.db.models.loading.get_model` gets you a second deprecation warning, so this does not help.  But it points in the right direction. The `loading` module has the pointers to the new locations.  So you can look in `loading.py` to see where you should import it from.  In this case you should use `django.apps.apps.get_model`.

Note: I am not using the django-swappable-models project, but this is currently the top link when Googling for `django.db.models.get_model is deprecated.` :-)

**Comment by sheppard** [comment]
Thanks for the heads up!

**Comment by sheppard** [comment]
Fixed in #9

**Comment by 42force** [comment]
Hi, has this been resolved?

**Comment by mauritsvanrees** [comment]
Yes, according to the [above comment](https://github.com/wq/django-swappable-models/issues/6#issuecomment-137123140) this was fixed more than three years ago in pull request #9.  Looking at the [commit](https://github.com/wq/django-swappable-models/pull/9/commits/79f45e2d080abad5441d6d7fa3052ec19f19bfd7) this was added already in swapper version 0.3.0.
